version: '3'

services:
  database:
    image: mysql:5.7
    volumes:
      - ./dockers/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      app_network:
        ipv4_address: 192.168.2.2

  app:
    build: ./dockers
    privileged: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      app_network:
        ipv4_address: 192.168.2.11

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
